// index
export class CarData {
  img: ResourceStr;
  text: string;

  constructor(img: ResourceStr, text: string) {
    this.img = img;
    this.text = text;
  }
}

export class classify {
  img: ResourceStr;
  text: string;

  constructor(img: ResourceStr, text: string) {
    this.img = img;
    this.text = text;
  }
}

export class classify2 {
  img: ResourceStr;
  text: string;

  constructor(img: ResourceStr, text: string) {
    this.img = img;
    this.text = text;
  }
}

export class inform {
  img: ResourceStr;
  text: string;
  date: string;

  constructor(img: ResourceStr, text: string, date: string) {
    this.img = img;
    this.text = text;
    this.date = date;
  }
}

export class plan {
  img: ResourceStr;
  text1: string;
  text2: string;
  text3: string;
  text4: string;
  showDetails: boolean;

  constructor(img: ResourceStr, text1: string, text2: string, text3: string, text4: string) {
    this.img = img;
    this.text1 = text1;
    this.text2 = text2;
    this.text3 = text3;
    this.text4 = text4;
    this.showDetails = false;
  }
}

export class Defect {
  img: ResourceStr;
  text1: string;
  text2: string;

  constructor(img: ResourceStr, text1: string, text2: string) {
    this.img = img;
    this.text1 = text1;
    this.text2 = text2;

  }
}

export class Mydata {
  img: ResourceStr;
  text1: string;
  text2: String;

  constructor(img: ResourceStr, text1: string,text2: String) {
    this.img = img;
    this.text1 = text1;
    this.text2 = text2;
  }
}